### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LvanCham** [JessYanCoding/MVPArms-Module-Template#1]
Error:(4, 0) Cannot get property 'android' on extra properties extension as it does not exist
<a href="openFile:D:\AndroidStudioWork\MyTs\mvp\build.gradle">Open File</a>

**Comment by JessYanCoding** [comment]
你只给这一点报错信息, 并且不提供 AndroidStuido 版本, 以及使用方式和描述使用场景的话, 我是不能够帮你解决问题的

**Comment by JessYanCoding** [comment]
你手动导入的 config.gradle 但并没有在根目录的 build.gradle 添加 apply from: "config.gradle"
