### ISSUE TITLE
关于兼容最新的 AndroidStudio 稳定版（3.1.3）

### ISSUE THREAD

**Issue by w4mxl** [JessYanCoding/MVPArms-Module-Template#2]
您好，最近收到 AndroidStudio 3.1.3 稳定版的更新提醒，升级过程快结束的时候出现模版不兼容的提示。为了不影响模版使用，取消了升级。这里想问下您近期有计划升级一下模版适配 AndroidStudio 3.1.3吗？

另外还有一点有建议，希望能在README中注明当前模版已适配的是AndroidStudio拿个版本。谢谢。

![1530529717701](https://user-images.githubusercontent.com/3645496/42160994-cd1af19c-7e2b-11e8-8836-1715e1ef94ce.jpg)

**Comment by JessYanCoding** [comment]
1. 不用注明模板支持哪些 AndroidStudio 版本, 因为 README 最上面大字已经写的很清楚了, 只保证能支持 AndroidStudio 最新的稳定版, 其他版本不能支持, 那就请升级, 可能你还是没认真看 (这个问题我都回答烦了, 所以写到了 README 上最显眼的位置, 尊重我请认真看完 README 谢谢)

2. 我想你可能是第一次用模板, AndroidStudio 升级时, 有些时候是会提示你模板冲突, 并提示你删除模板的, 这个并不是模板不支持即将升级的 AndroidStudio 版本, 点确定升级完成后, 将 Github 上面的模板重新复制进去即可 (AndroidStudio 一更新, 我会立即确认模板是否可用, 所以不用担心最新版是否可用)

**Comment by w4mxl** [comment]
您好，首先感谢回复。

说明一下哦，有认真读完README。是我理解有误，有看到保证能支持 AndroidStudio 最新的稳定版，但是以为最新稳定版本（3.1.3）刚出来您可能因为忙还没来得及适配。（现在知道您会第一时间确认可用）

我确实刚开始使用模版，所以对模版这块用的比较小心些了。

**Comment by JessYanCoding** [comment]
好的
