### ISSUE TITLE
请问mrvArt有一键生成的框架吗

### ISSUE THREAD

**Issue by flyjin** [JessYanCoding/MVPArms-Module-Template#4]
请问mrvArt有一键生成的框架吗

**Comment by JessYanCoding** [comment]
只有页面生成，https://github.com/JessYanCoding/MVPArmsTemplate/tree/master/MVPArtTemplate  ，框架生成其实使用 MVPArms Module 模板里面的模板代码改一下导入的包名就可以了，基本和 MVPArms 的代码没什么变化
