### ISSUE TITLE
大佬，我第一步导入就报错，按照wiki做了啊

### ISSUE THREAD

**Issue by vance0901** [JessYanCoding/MVPArms-Module-Template#9]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':userterminal2:javaPreCompileDebug'.
> Could not resolve all files for configuration ':userterminal2:debugAnnotationProcessorClasspath'.
   > Failed to transform artifact 'butterknife-compiler.jar (com.jakewharton:butterknife-compiler:9.0.0)' to match attributes {artifactType=processed-jar, org.gradle.usage=java-runtime-jars}.
      > Execution failed for JetifyTransform: C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.jakewharton\butterknife-compiler\9.0.0\fb0231ca8b0210c77e6ce1611e756bc2785efba1\butterknife-compiler-9.0.0.jar.
         > Failed to transform 'C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.jakewharton\butterknife-compiler\9.0.0\fb0231ca8b0210c77e6ce1611e756bc2785efba1\butterknife-compiler-9.0.0.jar' using Jetifier. Reason: The given artifact contains a string literal with a package reference 'android.support.v4.content' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.. (Run with --stacktrace for more details.)

就这个错误，奇怪。单独demo hello world 用的androidx 是可以跑起来的

**Comment by JessYanCoding** [comment]
报错不是模板的问题，这个是你自己项目的环境引起的，而且模板和框架都还没支持 androidx

**Comment by kh1011** [comment]
把 butterknifeSdkVersion 改成
> "10.0.0"
